# Generated by Django 3.2.7 on 2022-01-30 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Unique ID')),
                ('success', models.BooleanField(verbose_name='Successful')),
                ('score_time', models.IntegerField(verbose_name='Score Time')),
                ('elapsed_time', models.IntegerField(verbose_name='Elapsed Time')),
                ('bonus_time', models.IntegerField(verbose_name='Bonus Time')),
                ('gem_count', models.IntegerField(verbose_name='Gem Count')),
                ('gem_total', models.IntegerField(verbose_name='Gem Total')),
                ('fps', models.FloatField(verbose_name='Approximate FPS')),
                ('frames_count', models.IntegerField(verbose_name='Frame Count')),
                ('frames_time', models.IntegerField(verbose_name='Frame Time')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Unique ID')),
                ('file', models.FileField(max_length=255, upload_to='uploads')),
                ('name', models.TextField(verbose_name='File Name')),
                ('hash', models.TextField(max_length=128, verbose_name='File Hash')),
                ('upload_date', models.DateTimeField(verbose_name='Upload date')),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Unique ID')),
                ('os', models.CharField(choices=[('mac', 'macOS'), ('windows', 'Windows'), ('wine', 'Wine')], max_length=8, verbose_name='OS')),
                ('run_date', models.DateTimeField(verbose_name='Run Date')),
                ('error', models.TextField(null=True, verbose_name='Error Message')),
                ('score', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='run', to='recapp.score')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='recapp.submission')),
            ],
        ),
    ]
