# Generated by Django 3.2.7 on 2022-01-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='score',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Unique ID'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(max_length=255, upload_to='uploads', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Unique ID'),
        ),
    ]
