# Generated by Django 3.2.7 on 2022-01-31 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recapp', '0004_auto_20220130_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='level_name',
            field=models.TextField(default='', verbose_name='Level Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='mission',
            field=models.TextField(default='', verbose_name='Mission File'),
            preserve_default=False,
        ),
    ]
