# Generated by Django 3.2.7 on 2022-02-05 22:44
import re
from django.db import migrations, models

import recapp.models


def guess_tas(apps, schema_editor):
    Submission = apps.get_model('recapp', 'Submission')
    for sub in Submission.objects.all():
        if recapp.models.guess_tas(sub):
            sub.is_tas = True
            sub.save()


class Migration(migrations.Migration):

    dependencies = [
        ('recapp', '0005_auto_20220131_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_tas',
            field=models.BooleanField(default=False, verbose_name='Is TAS'),
            preserve_default=False,
        ),
        migrations.RunPython(guess_tas)
    ]
