# Generated by Django 3.2.7 on 2022-02-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recapp', '0007_alter_submission_is_tas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='os',
            field=models.TextField(max_length=32, verbose_name='OS'),
        ),
    ]
